language: php
services:
    - postgresql

php:
    - 5.5
    - 5.6
    - 7.0

script:
    - composer self-update
    - composer install
    - ./vendor/bin/phpunit --configuration phpunit.travis.xml.dist --coverage-clover tmp/clover.xml

before_script:
    - psql -c 'create database pseudoorm;' -U postgres
